# Generated by Django 4.1.5 on 2023-02-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzduotis',
            name='terminas',
        ),
        migrations.AlterField(
            model_name='uzduotis',
            name='sukurta',
            field=models.DateField(blank=True, null=True, verbose_name='Sukūrimo data:'),
        ),
    ]
