# Generated by Django 4.1.5 on 2023-02-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_remove_uzduotis_terminas_alter_uzduotis_sukurta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzduotis',
            name='sukurta',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sukūrimo data:'),
        ),
    ]
